const codeIsoAirport = [
  { code: "ABC", label: "Aeropuerto de Albacete " },
  { code: "AEP", label: "Aeroparque Jorge Newbery" },
  { code: "AFA", label: "	Aeropuerto Internacional Suboficial Ayudante Santiago Germano" },
  { code: "AGP", label: "Aeropuerto de Málaga-Costa del Sol" },
  { code: "AGT", label: "Aeropuerto Internacional Guaraní" },
  { code: "AMS", label: "Aeropuerto de Ámsterdam-Schiphol" },
  { code: "ANF", label: "Aeropuerto Andrés Sabella" },
  { code: "AOL", label: "Aeropuerto Internacional de Paso de los Libres" },
  { code: "ARI", label: "Aeropuerto Internacional Chacalluta" },
  { code: "ARN", label: "Aeropuerto de Estocolmo-Arlanda" },
  { code: "ASU", label: "	Aeropuerto Internacional Silvio Pettirossi" },
  { code: "ATH", label: "Aeropuerto Internacional Eleftherios Venizelos" },
  { code: "AUA", label: "Aeropuerto Internacional Reina Beatrix" },
  { code: "BBA", label: "Aeródromo Balmaceda" },
  { code: "BCN", label: "Aeropuerto de Barcelona-El Prat" },
  { code: "BIN", label: "	Aeropuerto de Bamiyán" },
  { code: "BIO", label: "Aeropuerto de Bilbao" },
  { code: "BOD", label: "Aeropuerto de Burdeos-Mérignac" },
  { code: "BOG", label: "Aeropuerto Internacional El Dorado" },
  { code: "BPM", label: "Base Aérea de Bagram" },
  { code: "BRC", label: "Aeropuerto Internacional Teniente Luis Candelaria " },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },
  { code: "", label: "" },







];
export default codeIsoAirport;


  // { code: "ATL", label: "Atlanta" },
  // { code: "BOS", label: "Boston" },
  // { code: "CHI", label: "Chicago" },
  // { code: "DAL", label: "Dallas" },
  // { code: "DEN", label: "Denver" },
  // { code: "LAX", label: "Los Angeles" },
  // { code: "NYC", label: "New York City" },
  // { code: "PHX", label: "Phoenix" },
  // { code: "SAN", label: "San Diego" },
  // { code: "SEA", label: "Seattle" },
  // { code: "WAS", label: "Washington" },
